# Generated by Django 3.2.6 on 2021-08-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesition',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='requesition',
            name='Status',
            field=models.CharField(choices=[('P', 'PENDING'), ('A', 'ACCEPTED'), ('PD', 'PARTIALLY DELIVERED'), ('D', 'DELIVERED')], default='P', max_length=2),
        ),
    ]
