# Generated by Django 3.2.6 on 2021-08-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210827_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesition',
            name='Status',
            field=models.CharField(choices=[('A', 'PENDING'), ('B', 'ACCEPTED'), ('C', 'PARTIALLY DELIVERED'), ('D', 'DELIVERED')], default='A', max_length=2),
        ),
    ]
