# Generated by Django 3.2.6 on 2021-09-01 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawBatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReqToRaw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_needed', models.IntegerField()),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rawbatch')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.requesition')),
            ],
        ),
        migrations.AddField(
            model_name='rawbatch',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rawmaterial'),
        ),
    ]
