# Generated by Django 3.2.6 on 2021-09-01 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210901_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawbatch',
            old_name='type',
            new_name='tp',
        ),
    ]
